/**
 * **Every scenario's survivor count sits inside its ladder position's band, or is registered outside
 * it** — GitHub issue **#234**, [§ D537](../../../../DECISIONS.md). Nothing here simulates.
 *
 * The band is `data/scenario-survivor-bands.json`: chosen, drafted for the owner's approval, and read
 * by this file alone. The counts are `data/scenario-survivors.json`: measured, generated by
 * `regenerateSurvivors.test-helper.ts` and pinned by `survivorSweep.test.ts`. The rules that join the
 * two — judged at the base rung, unjudged configurations out of the denominator, suppressed ones in
 * it, and a zero over suppressed runs told apart from a zero over measured ones — are stated with
 * their reasons in `survivorBands.test-helper.ts`'s docstring, which is the one place they live.
 *
 * ## The register, and why each entry names a verdict rather than only a scenario
 *
 * {@link OUTSIDE_THEIR_BAND} has `campaign/difficultyCurve.test.ts#DROPDOWN_CLEARS`'s shape and
 * `honesty.test.ts`'s rule under it: a scenario outside its band must be in it, and a scenario in it
 * must still be outside. An entry leaves on the commit that moves its scenario inside, by demand or
 * fabric and never by a bar (`docs/33` DC-R1) — which is #234's rebalance, not this file's.
 *
 * Each entry records **which side, and over what runs**, because that is what a rebalance has to read:
 * a scenario below its band over runs that measured and one below it over runs that all refused their
 * own mean are different problems, and a regeneration that turns one into the other should go red
 * rather than be absorbed. The counts are deliberately **not** written into the entries. They are
 * derived from the table on every run and printed in the failure sentence, so a regeneration that
 * moves a count without moving a verdict — GitHub issue #467 regenerates this table — cannot leave a
 * stale number behind in prose.
 *
 * ## The controls run on the real table
 *
 * `goalRates.test.ts`'s discipline, which `survivors.test.ts` inherits: every control mutates a clone
 * of the shipped table rather than a hand-built one. Where a control needs particular shares it reads
 * them from a band document it owns ({@link controlBands}), so it tests the reading and not the
 * drafted figures — the owner can move every figure in the data file without touching a control.
 */

import { readFile } from 'node:fs/promises';

import { beforeAll, describe, expect, it } from 'vitest';

import { SCENARIO_SURVIVORS_PATH } from './regenerateSurvivors.test-helper.js';
import {
  CAMPAIGN_PATH,
  SURVIVOR_BANDS_PATH,
  admittedCountsOf,
  bandForPosition,
  bandReadingOf,
  decodeSurvivorBands,
  isOutside,
  registerDisagreements,
  sampleSizeIssue,
  survivorBandIssues,
  type OutsideVerdict,
  type SurvivorBand,
  type SurvivorBands,
} from './survivorBands.test-helper.js';
import type { PublishedSurvivorScenario, PublishedSurvivors } from './survivors.js';

/**
 * **Scenarios outside their ladder position's band**, read on 2026-09-10 against the approved band
 * and the survivor table GitHub issue #467 re-measured on `88c0f0ad`, after the price schedule
 * withheld the weight-set selector and the arrival predictor and priced the other dials (§ D535).
 *
 * Eight of ten, and every one is **below**: too few ways through, none too many. Stages 9 and 10 are
 * below over runs that all refused their own mean, which is the distinction #234's comment of
 * 2026-09-10 asks a reader to keep; the other six had at least one configuration that stood behind
 * its numbers. The two inside are stages 3 and 5, and **inside is not rebalanced**: the one way
 * through stage 3 and the one through stage 5 are shipped profiles picked from the dropdown, which
 * § D528 clause 2 forbids from position three and `campaign/difficultyCurve.test.ts#DROPDOWN_CLEARS`
 * holds.
 *
 * **Stage 7 joined on #467, and a rebalance should read what moved first.** On the table measured on
 * `4159520` it was inside, at 2 of 24 through two dial edits; re-measured, it is 0 of 24. The twelve
 * dial edits are not the same configurations: the same sample seed now draws them from 511 bundles
 * where it drew from 11. So the table says none of the twelve drawn gets through, not that the two
 * earlier ways through were closed, and a table drawn on another seed could read stage 7 inside again
 * with nothing in the campaign moved.
 *
 * The owner approved the band as drafted on 2026-09-10, so every entry is a scenario outside an
 * approved band. If the band moves, this register moves with it on the same commit, and that is the
 * band moving rather than a scenario.
 */
const OUTSIDE_THEIR_BAND: Readonly<Record<string, OutsideVerdict>> = Object.freeze({
  'stage-1-first-call': 'below',
  'stage-2-morning-rush': 'below',
  'stage-4-two-banks': 'below',
  'stage-6-the-tall-one': 'below',
  'stage-7-prove-it': 'below',
  'stage-8-the-headline-address': 'below',
  'stage-9-both-ways-at-once': 'below-over-suppressed-runs',
  'stage-10-the-bed-and-the-visitor': 'below-over-suppressed-runs',
});

let table: PublishedSurvivors;
let rawBands: unknown;
let bands: SurvivorBands;
let campaignIds: readonly string[];

beforeAll(async () => {
  table = JSON.parse(await readFile(SCENARIO_SURVIVORS_PATH, 'utf8')) as PublishedSurvivors;
  rawBands = JSON.parse(await readFile(SURVIVOR_BANDS_PATH, 'utf8')) as unknown;
  bands = decodeSurvivorBands(rawBands);
  const campaign = JSON.parse(await readFile(CAMPAIGN_PATH, 'utf8')) as {
    readonly stages: readonly { readonly id: string }[];
  };
  campaignIds = campaign.stages.map((stage) => stage.id);
});

/* -------------------------------------------------------------------------- *
 * Fixtures the controls own
 * -------------------------------------------------------------------------- */

type Writable<T> = T extends readonly (infer U)[]
  ? Writable<U>[]
  : T extends object
    ? { -readonly [K in keyof T]: Writable<T[K]> }
    : T;

interface BaseCounts {
  readonly examined?: number;
  readonly survivors?: number;
  readonly unjudged?: number;
  readonly suppressed?: number;
}

/**
 * A clone of one shipped scenario with its **base** rung's counts replaced.
 *
 * Only the four counts the reading consumes are set, so the clone is not a table
 * `validatePublishedSurvivors` would accept — its strata no longer sum — and it does not need to be:
 * that consistency is asserted on the real table by `survivors.test.ts`, and a control here asks one
 * question of the reading and nothing else.
 */
function withBase(
  scenario: PublishedSurvivorScenario,
  counts: BaseCounts,
  diagnosis: string | null = scenario.diagnosis,
): PublishedSurvivorScenario {
  const copy = JSON.parse(JSON.stringify(scenario)) as Writable<PublishedSurvivorScenario>;
  copy.diagnosis = diagnosis;
  const base = copy.steps.find((step) => step.stepId === null);
  if (base === undefined) throw new Error(`${scenario.id} publishes no base rung to mutate`);
  Object.assign(base, counts);
  return copy as PublishedSurvivorScenario;
}

function scenarioAt(predicate: (scenario: PublishedSurvivorScenario) => boolean, what: string) {
  const found = table.scenarios.find(predicate);
  if (found === undefined) throw new Error(`the shipped table has no ${what}`);
  return found;
}

function shareSchema(value: number) {
  return { type: 'number', unit: 'share', min: 0, max: 1, default: value, activeWhen: null } as const;
}

function bandOf(from: number, to: number | null, minShare: number, maxShare: number): SurvivorBand {
  return {
    fromPosition: from,
    toPosition: to,
    minShare,
    maxShare,
    schema: { minShare: shareSchema(minShare), maxShare: shareSchema(maxShare) },
    note: 'CHOSEN: a control figure, owned by the test.',
  };
}

/** A band document the controls own: 1–2 in `[0.25, 0.5]`, every later position in `[0, 0.2]`. */
function controlBands(approval: 'draft' | 'approved' = 'draft'): SurvivorBands {
  return {
    version: 1,
    provenance: {
      kind: 'chosen',
      approval,
      ruling: 'a control, owned by survivorBands.test.ts',
      draftedOn: '2026-09-10',
      approvedOn: approval === 'approved' ? '2026-09-10' : null,
      approvedAtSampleSize: approval === 'approved' ? 12 : null,
    },
    bands: [bandOf(1, 2, 0.25, 0.5), bandOf(3, null, 0, 0.2)],
  };
}

function readingsOf(scenarios: readonly PublishedSurvivorScenario[], against: SurvivorBands) {
  return scenarios.map((scenario) => bandReadingOf(scenario, against));
}

/** The shipped table with one scenario replaced, read against the shipped band. */
function readingsWith(replacement: PublishedSurvivorScenario) {
  return readingsOf(
    table.scenarios.map((scenario) => (scenario.id === replacement.id ? replacement : scenario)),
    bands,
  );
}

/** The counts at each edge of a scenario's own band, at the `k` its base rung was judged over. */
function edgesOf(scenario: PublishedSurvivorScenario) {
  const reading = bandReadingOf(scenario, bands);
  const judged = reading.examined;
  return { judged, ...admittedCountsOf(reading.band, judged) };
}

/* -------------------------------------------------------------------------- *
 * 1 — The band is authored, chosen, and covers the ladder
 * -------------------------------------------------------------------------- */

describe('the survivor band is authored in data, chosen, and covers every position', () => {
  it('passes its own schema', () => {
    expect(survivorBandIssues(rawBands)).toEqual([]);
  });

  it('holds the survivor table to the sample size the band was approved at', () => {
    // A share is survivors over the affordable census plus `sampleSize` dial draws, so a table
    // regenerated at another sample size moves every share without any scenario moving.
    expect(bands.provenance.approval).toBe('approved');
    expect(sampleSizeIssue(bands, table)).toBeUndefined();
    const resampled = { ...table, provenance: { ...table.provenance, sampleSize: table.provenance.sampleSize * 2 } };
    expect(sampleSizeIssue(bands, resampled)).toMatch(/approved against 12/u);
    expect(sampleSizeIssue(controlBands('draft'), resampled)).toBeUndefined();
  });

  it('declares itself chosen, and says whether the owner has approved it', () => {
    expect(bands.provenance.kind).toBe('chosen');
    expect(['draft', 'approved']).toContain(bands.provenance.approval);
    for (const band of bands.bands) expect(band.note.startsWith('CHOSEN:'), band.note).toBe(true);
  });

  it('gives every position the survivor table publishes a band', () => {
    expect(table.scenarios.length, 'the table publishes no scenario').toBeGreaterThan(0);
    for (const scenario of table.scenarios) {
      expect(bandForPosition(bands, scenario.ladderPosition), scenario.id).toBeDefined();
    }
  });

  it('reads each scenario at the position data/campaign.json puts it', () => {
    /*
     * `validatePublishedSurvivors` checks `ladderPosition` against the table's own row. The band is
     * indexed by it, so this checks the row order against the campaign's as well: a table assembled
     * in another order would otherwise judge every scenario against its neighbour's band.
     */
    expect(table.scenarios.map((scenario) => scenario.id)).toEqual(campaignIds);
    for (const [index, scenario] of table.scenarios.entries()) {
      expect(scenario.ladderPosition, scenario.id).toBe(index + 1);
    }
  });

  it('leaves every scenario a count its band admits, at the k it was judged over', () => {
    /*
     * A band narrower than the count can resolve is a band no rebalance can reach: at seven
     * configurations judged, a ceiling of a tenth admits no survivor and the floor asks for one.
     */
    for (const reading of readingsOf(table.scenarios, bands)) {
      if (reading.judged <= 0) continue;
      const { low, high } = admittedCountsOf(reading.band, reading.judged);
      expect(low, `${reading.scenarioId}: the band admits no count over ${String(reading.judged)}`).toBeLessThanOrEqual(high);
    }
  });
});

/* -------------------------------------------------------------------------- *
 * 2 — The check: inside, or registered outside, in both directions
 * -------------------------------------------------------------------------- */

describe('every scenario sits inside its position’s band, or is registered outside it', () => {
  it('matches the register exactly, in both directions', () => {
    const readings = readingsOf(table.scenarios, bands);
    /* The guard on the guard: a check that read nothing would pass by asserting nothing. */
    expect(readings.length).toBe(table.scenarios.length);
    expect(readings.length).toBeGreaterThan(0);
    expect(
      registerDisagreements(readings, OUTSIDE_THEIR_BAND),
      'a scenario and its band disagree with the register. Either the campaign moved — #234’s ' +
        'rebalance, which is the point — or the table was regenerated, or the band was approved at ' +
        'different figures; the sentence says which scenario and every count it rests on.',
    ).toEqual([]);
  });

  it('names only scenarios the campaign ships', () => {
    for (const id of Object.keys(OUTSIDE_THEIR_BAND)) expect(campaignIds, id).toContain(id);
  });
});

/* -------------------------------------------------------------------------- *
 * 3 — The reading discriminates: controls on the real table
 * -------------------------------------------------------------------------- */

describe('the reading tells inside from outside', () => {
  const subject = () => scenarioAt((scenario) => scenario.ladderPosition === 1, 'position one');

  it('reads a count at its band’s lowest admitted edge as inside', () => {
    const { low } = edgesOf(subject());
    const reading = bandReadingOf(withBase(subject(), { survivors: low, unjudged: 0, suppressed: 0 }), bands);
    expect(reading.verdict).toBe('inside');
  });

  it('reads a count at its band’s highest admitted edge as inside', () => {
    const { high } = edgesOf(subject());
    const reading = bandReadingOf(withBase(subject(), { survivors: high, unjudged: 0, suppressed: 0 }), bands);
    expect(reading.verdict).toBe('inside');
  });

  it('reads one survivor over the ceiling as above', () => {
    const { high } = edgesOf(subject());
    const reading = bandReadingOf(withBase(subject(), { survivors: high + 1, unjudged: 0, suppressed: 0 }), bands);
    expect(reading.verdict).toBe('above');
    expect(isOutside(reading.verdict)).toBe(true);
  });

  it('reads one survivor under the floor as below', () => {
    const { low } = edgesOf(subject());
    const reading = bandReadingOf(withBase(subject(), { survivors: low - 1, unjudged: 0, suppressed: 0 }), bands);
    expect(reading.verdict).toBe('below');
    expect(isOutside(reading.verdict)).toBe(true);
  });

  it('refuses zero at a position whose share floor is zero — the floor is one survivor everywhere', () => {
    const later = scenarioAt((scenario) => scenario.ladderPosition >= 3, 'position three or later');
    const zero = withBase(later, { survivors: 0, unjudged: 0, suppressed: 0 }, null);
    expect(bandForPosition(controlBands(), later.ladderPosition)?.minShare).toBe(0);
    expect(bandReadingOf(zero, controlBands()).verdict).toBe('below');
    const one = withBase(later, { survivors: 1, unjudged: 0, suppressed: 0 }, null);
    expect(bandReadingOf(one, controlBands()).verdict).toBe('inside');
  });

  it('tells a zero over runs that all refused their mean from a zero over runs that measured', () => {
    const { judged } = edgesOf(subject());
    const allRefused = withBase(subject(), { survivors: 0, unjudged: 0, suppressed: judged }, null);
    expect(bandReadingOf(allRefused, bands).verdict).toBe('below-over-suppressed-runs');
    const oneMeasured = withBase(subject(), { survivors: 0, unjudged: 0, suppressed: judged - 1 }, null);
    expect(bandReadingOf(oneMeasured, bands).verdict).toBe('below');
  });

  it('keeps a suppressed survivor in the share rather than removing it', () => {
    /* The shipped table has scenarios whose every configuration was suppressed and one survived. */
    const { low, judged } = edgesOf(subject());
    const reading = bandReadingOf(
      withBase(subject(), { survivors: low, unjudged: 0, suppressed: judged }),
      bands,
    );
    expect(reading.verdict).toBe('inside');
  });

  it('takes unjudged configurations out of the denominator', () => {
    /* Position one in the control band is [0.25, 0.5]. 1 of 4 judged is inside; 1 of 20 is not. */
    const excluded = withBase(subject(), { examined: 20, survivors: 1, unjudged: 16, suppressed: 0 }, null);
    expect(bandReadingOf(excluded, controlBands()).verdict).toBe('inside');
    expect(bandReadingOf(excluded, controlBands()).judged).toBe(4);
    const counted = withBase(subject(), { examined: 20, survivors: 1, unjudged: 0, suppressed: 0 }, null);
    expect(bandReadingOf(counted, controlBands()).verdict).toBe('below');
  });

  it('reads a scenario with nothing judged as nothing-judged, never as a zero', () => {
    const nothing = withBase(subject(), { examined: 20, survivors: 0, unjudged: 20, suppressed: 0 }, null);
    const reading = bandReadingOf(nothing, controlBands());
    expect(reading.verdict).toBe('nothing-judged');
    expect(isOutside(reading.verdict)).toBe(true);
  });

  it('exempts a declared diagnosis from the floor, and from nothing else', () => {
    const diagnosis = 'the bank is one car short of the crowd it was let to.';
    const zero = withBase(subject(), { examined: 20, survivors: 0, unjudged: 0, suppressed: 0 }, diagnosis);
    expect(bandReadingOf(zero, controlBands()).verdict).toBe('diagnosis-exempt');
    expect(isOutside('diagnosis-exempt')).toBe(false);
    const tooMany = withBase(subject(), { examined: 20, survivors: 15, unjudged: 0, suppressed: 0 }, diagnosis);
    expect(bandReadingOf(tooMany, controlBands()).verdict).toBe('above');
  });

  it('judges the base rung and no other', () => {
    const scenario = scenarioAt((entry) => entry.steps.length > 1, 'scenario with a bought rung');
    const before = bandReadingOf(scenario, bands);
    const bought = JSON.parse(JSON.stringify(scenario)) as Writable<PublishedSurvivorScenario>;
    for (const step of bought.steps) {
      if (step.stepId !== null) {
        step.survivors = step.examined;
        step.suppressed = step.examined;
      }
    }
    const after = bandReadingOf(bought as PublishedSurvivorScenario, bands);
    expect(after.verdict).toBe(before.verdict);
    expect(after.survivors).toBe(before.survivors);
    const base = bandReadingOf(withBase(scenario, { survivors: before.examined - 1, unjudged: 0 }), bands);
    expect(base.survivors).toBe(before.examined - 1);
  });

  it('says in its own sentence when the band it read against is a draft', () => {
    const scenario = subject();
    expect(bandReadingOf(scenario, controlBands('draft')).sentence).toContain('draft');
    expect(bandReadingOf(scenario, controlBands('approved')).sentence).not.toContain('draft');
    expect(bandReadingOf(scenario, controlBands('approved')).sentence).toContain(scenario.id);
  });
});

/* -------------------------------------------------------------------------- *
 * 4 — The register goes red in both directions
 * -------------------------------------------------------------------------- */

describe('the register goes red in both directions', () => {
  const subject = () => scenarioAt((scenario) => scenario.ladderPosition === 1, 'position one');

  it('goes red when a listed scenario moves inside its band', () => {
    const id = subject().id;
    const register = { ...OUTSIDE_THEIR_BAND, [id]: 'below' as const };
    const { low } = edgesOf(subject());
    const lines = registerDisagreements(
      readingsWith(withBase(subject(), { survivors: low, unjudged: 0, suppressed: 0 }, null)),
      register,
    );
    expect(lines.some((line) => line.includes(`"${id}"`) && line.includes('Delete the entry'))).toBe(true);
  });

  it('goes red when an unlisted scenario falls outside its band', () => {
    const id = subject().id;
    const register = Object.fromEntries(
      Object.entries(OUTSIDE_THEIR_BAND).filter(([key]) => key !== id),
    ) as Record<string, OutsideVerdict>;
    const lines = registerDisagreements(
      readingsWith(withBase(subject(), { survivors: 0, unjudged: 0, suppressed: 0 }, null)),
      register,
    );
    expect(lines.some((line) => line.includes(`"${id}"`) && line.includes('is not registered'))).toBe(true);
  });

  it('goes red when a listed scenario is still outside, on the other side', () => {
    const id = subject().id;
    const register = { ...OUTSIDE_THEIR_BAND, [id]: 'above' as const };
    const lines = registerDisagreements(
      readingsWith(withBase(subject(), { survivors: 0, unjudged: 0, suppressed: 0 }, null)),
      register,
    );
    expect(lines.some((line) => line.includes(`"${id}"`) && line.includes('registered as above'))).toBe(true);
  });

  it('goes red on an entry naming a scenario the table does not publish', () => {
    const lines = registerDisagreements(readingsOf(table.scenarios, bands), {
      ...OUTSIDE_THEIR_BAND,
      'stage-11-nowhere': 'below',
    });
    expect(lines.some((line) => line.includes('"stage-11-nowhere"') && line.includes('does not publish'))).toBe(true);
  });
});

/* -------------------------------------------------------------------------- *
 * 5 — The schema refuses what the ruling forbids
 * -------------------------------------------------------------------------- */

interface LooseBand {
  fromPosition: number;
  toPosition: number | null;
  minShare: number;
  maxShare: number;
  schema: { minShare: { default: number }; maxShare: { default: number } };
  note: string;
  [key: string]: unknown;
}

interface LooseDocument {
  provenance: { kind: string; approval: string; approvedOn: string | null; approvedAtSampleSize?: number | null };
  bands: LooseBand[];
  [key: string]: unknown;
}

/** Set a band's two shares and their schema defaults together, so one control spoils one rule. */
function setShares(band: LooseBand, minShare: number, maxShare: number): void {
  band.minShare = minShare;
  band.maxShare = maxShare;
  band.schema.minShare.default = minShare;
  band.schema.maxShare.default = maxShare;
}

function issuesAfter(change: (document: LooseDocument) => void): readonly string[] {
  const document = JSON.parse(JSON.stringify(rawBands)) as LooseDocument;
  change(document);
  return survivorBandIssues(document);
}

function bandAt(document: LooseDocument, index: number): LooseBand {
  const band = document.bands.at(index);
  if (band === undefined) throw new Error(`the shipped band document has no band at ${String(index)}`);
  return band;
}

describe('the band’s schema refuses what the ruling forbids', () => {
  it('needs at least two bands to test an ordering on', () => {
    expect((rawBands as LooseDocument).bands.length).toBeGreaterThanOrEqual(2);
  });

  it('refuses a band that calls itself measured', () => {
    const issues = issuesAfter((document) => {
      document.provenance.kind = 'measured';
    });
    expect(issues.some((line) => line.includes('does not declare itself chosen'))).toBe(true);
  });

  it('refuses an approval with no date, and a draft with one', () => {
    expect(
      issuesAfter((document) => {
        document.provenance.approval = 'approved';
        document.provenance.approvedOn = null;
      }).some((line) => line.includes('approved and carries no approval date')),
    ).toBe(true);
    expect(
      issuesAfter((document) => {
        document.provenance.approval = 'draft';
        document.provenance.approvedOn = '2026-09-10';
      }).some((line) => line.includes('a draft that carries an approval date')),
    ).toBe(true);
  });

  it('refuses an approval that names no sample size, and a draft that names one', () => {
    // An approval is of shares at one survivor-table sample size, so it has to say which.
    expect(
      issuesAfter((document) => {
        document.provenance.approvedAtSampleSize = null;
      }).some((line) => line.includes('does not record approvedAtSampleSize')),
    ).toBe(true);
    expect(
      issuesAfter((document) => {
        document.provenance.approval = 'draft';
        document.provenance.approvedOn = null;
      }).some((line) => line.includes('a draft that records approvedAtSampleSize')),
    ).toBe(true);
  });

  it('refuses a band that admits the whole space — DC-1 as a reading of the count', () => {
    const issues = issuesAfter((document) => {
      const band = bandAt(document, -1);
      setShares(band, band.minShare, 1);
    });
    expect(issues.some((line) => line.includes('admits the whole space'))).toBe(true);
  });

  it('refuses a floor above its ceiling', () => {
    const issues = issuesAfter((document) => {
      setShares(bandAt(document, 0), 0.6, 0.5);
    });
    expect(issues.some((line) => line.includes('floor above its ceiling'))).toBe(true);
  });

  it('refuses positions that are not contiguous from one', () => {
    expect(
      issuesAfter((document) => {
        bandAt(document, 1).fromPosition += 1;
      }).some((line) => line.includes('not contiguous')),
    ).toBe(true);
    expect(
      issuesAfter((document) => {
        bandAt(document, 0).fromPosition = 2;
      }).some((line) => line.includes('does not start at position one')),
    ).toBe(true);
  });

  it('refuses a ladder whose last band is closed, so a new scenario would have none', () => {
    const issues = issuesAfter((document) => {
      const last = bandAt(document, -1);
      last.toPosition = last.fromPosition;
    });
    expect(issues.some((line) => line.includes('open-ended'))).toBe(true);
  });

  it('refuses a later band whose ceiling rises, whose floor rises, or which is wider', () => {
    expect(
      issuesAfter((document) => {
        setShares(bandAt(document, 0), 0.25, 0.5);
        setShares(bandAt(document, 1), 0, 0.6);
      }).some((line) => line.includes('ceiling rises')),
    ).toBe(true);
    expect(
      issuesAfter((document) => {
        setShares(bandAt(document, 0), 0, 0.5);
        setShares(bandAt(document, 1), 0.1, 0.4);
      }).some((line) => line.includes('floor rises')),
    ).toBe(true);
    expect(
      issuesAfter((document) => {
        setShares(bandAt(document, 0), 0.4, 0.6);
        setShares(bandAt(document, 1), 0, 0.5);
      }).some((line) => line.includes('wider than the band before it')),
    ).toBe(true);
  });

  it('refuses a schema whose default is not the shipped value', () => {
    const issues = issuesAfter((document) => {
      bandAt(document, 0).schema.maxShare.default = 0.9;
    });
    expect(issues.some((line) => line.includes('schema default'))).toBe(true);
  });

  it('refuses a note that does not say the figure is chosen', () => {
    const issues = issuesAfter((document) => {
      bandAt(document, 0).note = 'MEASURED: nothing of the kind.';
    });
    expect(issues.some((line) => line.includes('CHOSEN:'))).toBe(true);
  });

  it('refuses a key the schema does not declare', () => {
    const issues = issuesAfter((document) => {
      bandAt(document, 0)['minSurvivors'] = 0;
    });
    expect(issues.some((line) => line.includes('unrecognised key'))).toBe(true);
  });
});
