/**
 * The vocabulary of measurement: what a run records, and what a run summarizes to.
 *
 * docs/03-traffic-and-statistics.md § Part 5 is unambiguous about the shape of this module:
 *
 * > Persist **per-run records, not aggregates**, with the seed attached, so any run can be
 * > replayed exactly and results re-analyzed without re-simulating.
 *
 * So a {@link RunRecord} is a *dataset*, not a report. It carries one {@link PassengerRecord}
 * per leg, the raw load and queue samples, and the seed — and nothing derived. Every headline
 * number (AWT, WT95, % > 60 s, TTD, handling capacity, saturation) is computed from it by
 * `summarize.ts`, which means Phase 3 can re-window, re-threshold or re-percentile a stored
 * run without re-simulating it. Anything stored *and* derived would be a second source of
 * truth that could drift from the first.
 *
 * ## Two rules that decide most of the design
 *
 * **1. Window membership is by arrival time, and it is half-open.** A leg belongs to the
 * window `[startS, endS)` iff `startS <= arrivedAt < endS`, and a *journey* belongs to it iff
 * its first leg does. Arrival time is chosen over boarding or alighting time for a reason
 * that is easy to miss and expensive to get wrong: arrival time is generated by the traffic
 * model and is **identical across every dispatcher under comparison** (common random
 * numbers), whereas boarding time is an *output* of the dispatcher. Selecting by boarding
 * time would let a slow dispatcher push its own worst passengers past the window boundary and
 * report a better AWT for being worse. Half-open so that adjacent windows partition a run
 * exactly once, with no passenger counted twice and none dropped.
 *
 * The one deliberate exception is {@link HandlingCapacity}, which is a *throughput* measure
 * and must count events that occurred during the window rather than a cohort that arrived
 * during it. It says so on the type.
 *
 * **2. No mean for a diverging queue.** {@link SaturationDiagnosis} exists so that a saturated
 * configuration is reported as saturated rather than as an AWT. {@link RunSummary.awtIsValid}
 * is the flag Phase 3 reads to suppress the confidence interval.
 *
 * ## Conventions (see CLAUDE.md)
 *
 * - Time is simulated seconds from the kernel; nothing here reads a wall clock (invariant 3).
 * - Every field is `readonly`, every collection a copy.
 * - Empty statistics report `NaN`, never `0`. "No passengers waited" and "passengers waited
 *   zero seconds" are different facts, and a downstream confidence interval must not be able
 *   to confuse them.
 */

import type { SimTime } from '../kernel/types.js';
import type { CredentialGroup, Direction } from '../model/types.js';

/* -------------------------------------------------------------------------- *
 * Errors and versioning
 * -------------------------------------------------------------------------- */

/**
 * An impossible measurement: boarding a passenger who never arrived, a percentile outside
 * `[0, 100]`, a run record whose seed is missing.
 *
 * Thrown rather than returned, for the same reason `ModelError` is: a metric that silently
 * absorbs a contradiction becomes a confidently wrong number, which is the single failure
 * mode CLAUDE.md § Statistical discipline exists to prevent.
 */
export class MetricsError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'MetricsError';
  }
}

/**
 * Format version of {@link RunRecord} on disk.
 *
 * Bumped whenever a stored record's shape changes in a way that an older reader would
 * misinterpret. `parseRunRecord` refuses a version it does not know rather than guessing,
 * because a mis-parsed run record produces plausible statistics from the wrong data.
 */
export const METRICS_SCHEMA_VERSION = 1;

/* -------------------------------------------------------------------------- *
 * Percentiles
 * -------------------------------------------------------------------------- */

/**
 * How a percentile falls between two order statistics.
 *
 * Percentile is not one function — the literature has at least nine — so the method is
 * carried on every result that used it rather than being an unstated house convention. WT95
 * from two tools that disagree on interpolation is not a reproducibility bug anyone enjoys
 * finding.
 *
 * - `linear` — **the default.** Hyndman & Fan type 7, which is what NumPy, R's default and
 *   Excel's `PERCENTILE.INC` compute. The percentile at `p` sits at position
 *   `h = (n - 1) * p / 100` in the ascending order statistics, linearly interpolated between
 *   `x[floor(h)]` and `x[floor(h) + 1]`. Continuous in `p`, which matters because WT95 is
 *   compared between configurations that differ by fractions of a second.
 * - `nearest-rank` — the classical definition: the smallest observed value at or below which
 *   at least `p`% of the sample falls, i.e. `x[ceil(n * p / 100) - 1]`. Always an observed
 *   value, never interpolated. Discontinuous in `n`, so two runs with different passenger
 *   counts can report percentiles that jump; offered because some lift-industry reporting
 *   uses it and cross-checks need it.
 */
export const PERCENTILE_METHODS = ['linear', 'nearest-rank'] as const;

export type PercentileMethod = (typeof PERCENTILE_METHODS)[number];

/** Hyndman & Fan type 7. See {@link PERCENTILE_METHODS}. */
export const DEFAULT_PERCENTILE_METHOD: PercentileMethod = 'linear';

/* -------------------------------------------------------------------------- *
 * Histograms
 * -------------------------------------------------------------------------- */

/**
 * One bucket of a {@link Histogram}.
 *
 * Half-open `[lowerBound, upperBound)`, except the final bin of a histogram, which is closed
 * at the top so the maximum observation lands somewhere. {@link count} is how many samples
 * fell here; {@link weight} is their total weight, which for a time-weighted distribution is
 * **seconds**, not samples.
 */
export interface HistogramBin {
  readonly lowerBound: number;
  readonly upperBound: number;
  readonly count: number;
  readonly weight: number;
  /** `weight / totalWeight`, or `0` when the histogram is empty. */
  readonly fraction: number;
}

/**
 * A binned distribution, optionally weighted.
 *
 * Weighting is what makes "car occupancy over time" honest. A car that sits at 0.9 for two
 * minutes and at 0.1 for one second visited two load levels equally often and spent 99.2% of
 * its time full; an unweighted histogram of the samples would call that an even split. See
 * {@link LoadFactorStatistics}.
 */
export interface Histogram {
  readonly bins: readonly HistogramBin[];
  /** Samples that landed inside the bins. Excludes {@link underflow} and {@link overflow}. */
  readonly count: number;
  /** Total weight inside the bins. Equals {@link count} for an unweighted histogram. */
  readonly totalWeight: number;
  /** Samples below the first bin's lower bound. */
  readonly underflow: number;
  /** Samples above the last bin's upper bound. */
  readonly overflow: number;
  /** Weighted mean of the observations, or `NaN` when there are none. Not a bin midpoint. */
  readonly mean: number;
  /** Smallest observation, or `NaN` when there are none. */
  readonly min: number;
  /** Largest observation, or `NaN` when there are none. */
  readonly max: number;
}

/* -------------------------------------------------------------------------- *
 * Trend
 * -------------------------------------------------------------------------- */

/** An ordinary-least-squares fit of `y = intercept + slope * x`. */
export interface LinearTrend {
  readonly n: number;
  /** Units of `y` per unit of `x`. */
  readonly slope: number;
  readonly intercept: number;
  /** Coefficient of determination, `0` when `y` has no variance. */
  readonly rSquared: number;
  /**
   * Residual standard deviation about the fitted line, in units of `y`
   * (`sqrt(RSS / (n - 2))`). `Infinity` for `n < 3`.
   *
   * This is the scatter the fit did **not** explain, and unlike {@link standardError} it is
   * not an inference statistic, so autocorrelation does not corrupt it: it is simply how far
   * the observations sit from the line. {@link SaturationThresholds.minGrowthToNoiseRatio}
   * uses it as the noise yardstick that the fitted growth has to beat.
   */
  readonly residualStdDev: number;
  /**
   * Standard error of {@link slope}, under the OLS assumption of independent residuals.
   *
   * `Infinity` for `n < 3` (no residual degrees of freedom). Queue-length series violate the
   * independence assumption badly — see {@link SaturationThresholds.minTStatistic}.
   */
  readonly standardError: number;
  /** `slope / standardError`. `0` when the slope is exactly zero. */
  readonly tStatistic: number;
  readonly meanX: number;
  readonly meanY: number;
}

/* -------------------------------------------------------------------------- *
 * Per-passenger records
 * -------------------------------------------------------------------------- */

/**
 * One leg of one passenger's journey, as recorded.
 *
 * This is the atom the whole metrics module is built from, and it is deliberately **raw**:
 * timestamps, not durations. `waitSeconds` is not a field because it is
 * `boardedAt - arrivedAt` and storing both invites the two to disagree after a hand edit or a
 * schema migration. Use {@link waitSecondsOf}, {@link rideSecondsOf} and
 * {@link legSecondsOf}.
 *
 * A leg with no {@link boardedAt} was still waiting when the run ended — which is
 * information, not an omission: unserved passengers are exactly the signature of saturation,
 * and they must survive into the record so `detectSaturation` can see them.
 *
 * Journey identity ({@link journeyId}) is what makes time-to-destination span a sky-lobby
 * transfer; see {@link JourneyRecord}.
 */
export interface PassengerRecord {
  /** Identity of *this leg*, unique within a run. `Passenger.id`. */
  readonly passengerId: string;
  /** Identity of the whole journey, stable across sky-lobby transfers. */
  readonly journeyId: string;
  /** 0 for the first leg, incrementing at each transfer. */
  readonly legIndex: number;
  /** Whether this leg ends at the journey's final destination. */
  readonly isFinalLeg: boolean;

  readonly originFloorId: string;
  /** Where *this leg* ends — the sky lobby, on a leg that transfers. */
  readonly destinationFloorId: string;
  /** Where the whole journey ends. Equal to {@link destinationFloorId} on the final leg. */
  readonly finalDestinationFloorId: string;
  readonly direction: Direction;

  /** Body mass in kilograms, as drawn from the `passengerMass` stream. */
  readonly massKg: number;
  readonly credentialGroup?: CredentialGroup | undefined;

  /**
   * When this leg's wait began — registration at the landing.
   *
   * **The window membership key.** Dispatcher-independent, so the same passenger falls in the
   * same window under every configuration being compared. See the module docstring.
   */
  readonly arrivedAt: SimTime;
  /** When the whole journey began. Equal to {@link arrivedAt} on the first leg. */
  readonly journeyStartedAt: SimTime;
  /** When the passenger entered the car, or absent if they were never served. */
  readonly boardedAt?: SimTime | undefined;
  /** When the passenger left the car, or absent if they never boarded or never arrived. */
  readonly alightedAt?: SimTime | undefined;
  /** The car that served this leg, when known. */
  readonly carId?: string | undefined;
  /** The bank that served this leg, when known. */
  readonly bankId?: string | undefined;
}

/** Seconds spent waiting at the landing on this leg, or `undefined` if never served. */
export function waitSecondsOf(record: PassengerRecord): number | undefined {
  return record.boardedAt === undefined ? undefined : record.boardedAt - record.arrivedAt;
}

/** Seconds spent in the car on this leg, or `undefined` until the passenger alights. */
export function rideSecondsOf(record: PassengerRecord): number | undefined {
  if (record.boardedAt === undefined || record.alightedAt === undefined) return undefined;
  return record.alightedAt - record.boardedAt;
}

/** Wait plus ride for this leg alone, or `undefined` until the passenger alights. */
export function legSecondsOf(record: PassengerRecord): number | undefined {
  return record.alightedAt === undefined ? undefined : record.alightedAt - record.arrivedAt;
}

/**
 * Every leg of one journey, and the journey-level timings that only exist across legs.
 *
 * Built by `buildJourneys()` from the flat leg records — the module never stores journeys,
 * because a journey is a *view* of its legs and storing it would duplicate them.
 *
 * This type is the reason `journeyId` exists. docs/03-traffic-and-statistics.md makes
 * time-to-destination a headline metric ("what destination dispatch optimizes; AWT alone
 * unfairly penalizes it"), and in a sky-lobby building the destination is two rides and a
 * walk away. Reporting the final leg's own duration as TTD would flatter every mixed-use
 * tower by hiding the first wait, the shuttle ride and the transfer.
 */
export interface JourneyRecord {
  readonly journeyId: string;
  /** The legs, ascending by `legIndex`. Always at least one. */
  readonly legs: readonly PassengerRecord[];
  readonly legCount: number;
  /** Origin of the first leg. */
  readonly originFloorId: string;
  /** Final destination as declared by the legs. */
  readonly finalDestinationFloorId: string;
  /**
   * When the journey began: the first leg's `arrivedAt`.
   *
   * **The window membership key for a journey**, so a journey belongs to exactly one window
   * however many legs it has.
   */
  readonly startedAt: SimTime;
  /** When the final leg alighted, or `undefined` while the journey is incomplete. */
  readonly completedAt?: SimTime | undefined;
  /** Whether a final leg exists *and* has alighted. */
  readonly isComplete: boolean;
  /**
   * Arrival at the first landing to alighting at the final one, **including** every transfer
   * wait and walk. `undefined` until the journey completes.
   *
   * A passenger standing in a sky lobby waiting for the second car has no time-to-destination
   * yet, and reporting the first leg's duration as one would be a lie in the flattering
   * direction.
   */
  readonly timeToDestinationSeconds?: number | undefined;
  /** Sum of the legs' waiting times, over the legs that boarded. */
  readonly totalWaitSeconds: number;
  /** Sum of the legs' ride times, over the legs that completed. */
  readonly totalRideSeconds: number;
  /**
   * Time spent neither waiting nor riding: walking across sky lobbies between legs.
   * `undefined` until the journey completes.
   */
  readonly transferSeconds?: number | undefined;
}

/* -------------------------------------------------------------------------- *
 * Samples
 * -------------------------------------------------------------------------- */

/**
 * What one car's load cell read at one instant.
 *
 * Sampled at load-change events, not on a timer: between two events the load is constant, so
 * an event-driven sample is exact rather than approximate. `summarize` treats the series as a
 * step function and weights each sample by the seconds until the next one for the same car —
 * which is why sampling on every board and alight is both sufficient and correct, and why a
 * sample taken before the report window still counts (its value holds into the window).
 */
export interface LoadSample {
  readonly at: SimTime;
  readonly carId: string;
  /** `massKg / ratedLoadKg`. Can exceed 1: 1.1 is the overload alarm, not the ceiling. */
  readonly loadFactor: number;
  readonly occupants: number;
  readonly massKg: number;
}

/** The three numbers a {@link LoadSample} needs from a car. `CarLoadSnapshot` satisfies it. */
export interface LoadReading {
  readonly loadFactor: number;
  readonly occupants: number;
  readonly massKg: number;
}

/**
 * How many people were waiting, building-wide, at one instant.
 *
 * The input to saturation detection. Explicit samples are preferred, because only the
 * simulation knows about passengers who left the queue for a reason other than boarding; when
 * a record has none, `queueLengthSeries()` derives an equivalent series from the arrival and
 * boarding times in the passenger records.
 */
export interface QueueSample {
  readonly at: SimTime;
  /** Total passengers waiting at landings. */
  readonly waiting: number;
  /** Optional per-floor breakdown, for diagnosing *where* a queue diverges. */
  readonly byFloorId?: Readonly<Record<string, number>> | undefined;
}

/* -------------------------------------------------------------------------- *
 * Windows
 * -------------------------------------------------------------------------- */

/**
 * A reporting window, half-open in simulated seconds: `[startS, endS)`.
 *
 * The rise-and-fall template reports the **peak 5 minutes**, not the whole run
 * (docs/03-traffic-and-statistics.md § Part 1), so the window is a first-class value that
 * travels with every summary rather than an implicit assumption about which numbers mean
 * what.
 */
export interface ReportWindow {
  /** Label for reporting, e.g. `full-run`, `peak-5min`. */
  readonly id: string;
  /** Inclusive lower bound. */
  readonly startS: SimTime;
  /** Exclusive upper bound. */
  readonly endS: SimTime;
}

/** Seconds spanned by a window. */
export function windowDurationS(window: ReportWindow): number {
  return window.endS - window.startS;
}

/** Whether an instant falls in `[startS, endS)`. */
export function windowContains(window: ReportWindow, at: SimTime): boolean {
  return at >= window.startS && at < window.endS;
}

/**
 * Whether a leg belongs to a window — **by arrival time**, never by boarding or alighting.
 *
 * See the module docstring: arrival times come from the traffic model and are identical
 * across the configurations being compared, so window membership cannot be shifted by the
 * thing under test.
 */
export function windowContainsArrival(window: ReportWindow, record: PassengerRecord): boolean {
  return windowContains(window, record.arrivedAt);
}

/** Whether a journey belongs to a window, by the arrival time of its first leg. */
export function windowContainsJourney(window: ReportWindow, journey: JourneyRecord): boolean {
  return windowContains(window, journey.startedAt);
}

/* -------------------------------------------------------------------------- *
 * The run record
 * -------------------------------------------------------------------------- */

/**
 * Everything one replication produced, and the seed that produced it.
 *
 * **CLAUDE.md invariant 5 lives on this type.** {@link seed} is not optional and is not a
 * convenience: it is what lets a stored record be replayed bit-for-bit
 * (`new StreamSet(runSeed(record))`), and `parseRunRecord` rejects a record without one
 * rather than loading a dataset nobody can reproduce.
 *
 * The seed is a **decimal string** because it is a 64-bit unsigned value: `bigint` does not
 * survive `JSON.stringify`, and `number` silently loses precision above 2^53. `runSeed()`
 * converts it back.
 */
export interface RunRecord {
  readonly schemaVersion: number;
  /** Identity of this replication, unique within an experiment. */
  readonly runId: string;
  /** The `StreamSet` master seed, as a decimal string. Invariant 5. */
  readonly seed: string;
  readonly buildingId?: string | undefined;
  readonly dispatcherProfileId?: string | undefined;
  readonly trafficProfileId?: string | undefined;
  readonly demandTemplateId?: string | undefined;
  /** Index of this replication within its batch, when it belongs to one. */
  readonly replication?: number | undefined;
  /** Population the demand was generated against, for handling capacity as % of population. */
  readonly population?: number | undefined;

  /** Simulated time the run started, in seconds. */
  readonly startedAt: SimTime;
  /**
   * Simulated time the run stopped — the horizon passed to `SimKernel.run(until)`.
   *
   * **Exclusive.** The full-run window is `[startedAt, endedAt)`, so pass the horizon you ran
   * to, not the timestamp of the last event; a passenger arriving at exactly `endedAt` falls
   * outside the window by the same half-open rule every other window obeys.
   */
  readonly endedAt: SimTime;
  /** The window this run intends to be reported over, when the demand template names one. */
  readonly reportWindow?: ReportWindow | undefined;

  /**
   * Every car in service during the run, whether or not it ever carried anybody.
   *
   * The fleet roster, not a derived list. `LoadFactorStatistics` needs it because an idle car
   * produces no {@link LoadSample} and would otherwise vanish from the occupancy
   * distribution, taking the evidence of over-provisioning with it — see that type. Optional
   * so a record written before the roster was tracked still parses; when it is absent the
   * cars seen in the samples are all the metric can know about.
   */
  readonly carIds?: readonly string[] | undefined;
  /** One entry per leg, in the order the legs arrived. */
  readonly passengers: readonly PassengerRecord[];
  readonly loadSamples: readonly LoadSample[];
  readonly queueSamples: readonly QueueSample[];
  /** Free-form provenance: weight vector id, sweep coordinates, anything Phase 3 wants back. */
  readonly metadata?: Readonly<Record<string, string | number | boolean>> | undefined;
}

/**
 * The master seed as a `bigint`, ready for `new StreamSet(...)`.
 *
 * @throws MetricsError if the stored seed is not a non-negative decimal integer — an
 *   unreplayable record is a broken record, not a record with a cosmetic flaw.
 */
export function runSeed(record: Pick<RunRecord, 'seed' | 'runId'>): bigint {
  if (!/^\d+$/.test(record.seed)) {
    throw new MetricsError(
      `Run "${record.runId}" carries seed "${record.seed}", which is not a decimal integer. Every run record must carry the seed that produced it (CLAUDE.md invariant 5) or it cannot be replayed.`,
    );
  }
  return BigInt(record.seed);
}

/* -------------------------------------------------------------------------- *
 * Saturation
 * -------------------------------------------------------------------------- */

/** Why {@link SaturationDiagnosis.saturated} came out the way it did. */
export const SATURATION_VERDICTS = [
  /** Queue length trends upward, materially and significantly. Statistics are invalid. */
  'diverging-queue',
  /** Fitted trend is flat, negative, or too small to matter. */
  'stable',
  /** Fewer samples than {@link SaturationThresholds.minSamples}: no verdict is possible. */
  'insufficient-samples',
] as const;

export type SaturationVerdict = (typeof SATURATION_VERDICTS)[number];

/**
 * The rule for calling a run saturated, and why every part of it is there.
 *
 * docs/03-traffic-and-statistics.md prescribes the test: "test for a positive trend in queue
 * length across the run. If present, mark the result `SATURATED` and suppress the AWT
 * confidence interval." The implementation fits an ordinary-least-squares line to
 * `(time, queueLength)` **over the reporting window** and then requires **all** of:
 *
 * 1. **Rate** — `slopePersonsPerMinute >= minSlopePersonsPerMinute`.
 * 2. **Magnitude** — `projectedGrowthPersons >= minProjectedGrowthPersons`.
 * 3. **Signal-to-noise** — `projectedGrowthPersons >= minGrowthToNoiseRatio * residualStdDev`.
 * 4. **Significance** — `tStatistic >= minTStatistic`. A weak sanity gate only.
 *
 * ## Why a rate alone is not enough: the window is not the run
 *
 * A rate threshold has to be paid for over some length of time before it means anything, and
 * the length of time here is **the reporting window, not the run**. `METRICS_PARAMETERS`
 * defaults `metrics.reportWindow` to `peak-5min`, so the fit that decides this verdict is
 * routinely 300 s long, not the 1800 s the 0.5 persons/min figure was derived against. Over
 * 300 s that same rate is only 2.5 persons of accumulated backlog, which is well inside the
 * ordinary sampling noise of a *stationary* batch-arrival queue — and the t-statistic cannot
 * rescue it, because queue-length residuals are autocorrelated and inflate `t` (see below).
 *
 * Measured, on a stationary queue with Poisson arrivals and i.i.d. exponential waits and
 * therefore **no trend by construction**: a rate-only rule flags 12–30 % of runs as
 * `SATURATED` over a 300 s window (0 % over 1800 s, which is why the defect was invisible).
 * Each false positive sets {@link RunSummary.awtIsValid} to `false`, and Phase 3 then either
 * suppresses one good confidence interval in four or drops those replications — which is
 * selection on the outcome variable, because the runs whose queue happened to drift up are
 * exactly the runs with the longest waits. Adding gates 2 and 3 takes the same measurement to
 * 0.0–1.8 % while still catching a queue that is genuinely running away (98 %+ detection at
 * 4 persons/min of true growth over a 5-minute window).
 *
 * ## How the gates divide the work
 *
 * Gates 1 and 2 are both absolute, and whichever is stricter binds: over a 300 s window
 * gate 2 binds (8 persons is 1.6 persons/min), over the recommended 1800 s run gate 1 binds
 * (0.5 persons/min is 15 persons). So a short window is required to show proportionally more
 * evidence, which is the whole point.
 *
 * Gate 3 is what makes the rule scale-free. A lobby whose queue swings between 40 and 60
 * people all through the peak produces a much noisier trend estimate than one that swings
 * between 2 and 6, and an absolute person threshold cannot tell those apart. Comparing the
 * fitted growth against the *residual* scatter can.
 *
 * Gate 4 is deliberately not trusted on its own. Queue length is strongly autocorrelated (the
 * queue one sample from now is mostly the queue now), which violates the independent-residuals
 * assumption behind the OLS standard error and inflates the t-statistic; a perfectly stable
 * queue can produce a "significant" slope of a hundredth of a person per minute. It is kept
 * only to stop a large slope fitted through pure noise from counting.
 */
export interface SaturationThresholds {
  /**
   * Fewest samples that can produce a verdict. Below this the answer is
   * `insufficient-samples` and {@link SaturationDiagnosis.saturated} is `false` — an unknown
   * is reported as unknown rather than as "fine".
   */
  readonly minSamples: number;
  /**
   * Persons per minute of fitted growth at or above which the queue may count as diverging.
   *
   * **Default 0.5.** The recommended rise-and-fall run is 30 minutes
   * (`data/traffic-profiles.json → demandTemplates`), so over a *whole-run* window 0.5
   * persons/min is a queue that ends ~15 people longer than it started — more than half a
   * 21-person car load that the system never clears.
   *
   * Note what that derivation assumes: a 30-minute fit. It is therefore only the binding gate
   * for windows **longer** than 30 minutes; for anything shorter
   * {@link minProjectedGrowthPersons} is stricter and binds instead. See the interface
   * docstring.
   */
  readonly minSlopePersonsPerMinute: number;
  /**
   * Persons of fitted backlog accumulated **across the fitted window** at or above which the
   * queue may count as diverging — `slope * windowSeconds`, the quantity reported as
   * {@link SaturationDiagnosis.projectedGrowthPersons}.
   *
   * **Default 8.** Stated in persons rather than persons per minute precisely because the
   * window length varies: this is the gate that makes a 5-minute fit demand proportionally
   * more evidence than a 30-minute one. Eight people is ~0.4 of a 21-person design car load
   * (80 % of a 26-person car) still standing at the landings that the system never came back
   * for — a backlog a single extra trip cannot clear. Empirically it is also the point at
   * which the false-positive rate on a stationary 300 s window drops to ~1 % or below for
   * realistic loads.
   */
  readonly minProjectedGrowthPersons: number;
  /**
   * How many times the residual scatter the fitted growth must exceed:
   * `projectedGrowthPersons >= minGrowthToNoiseRatio * residualStdDev`.
   *
   * **Default 4.** The noise-aware gate, and the only one that adapts to how busy the
   * building is. `residualStdDev` is the queue's own scatter about the fitted line
   * ({@link LinearTrend.residualStdDev}); a growth of eight people means something quite
   * different on a queue that sits within ±1 of its mean than on one that swings by ±15.
   *
   * Four rather than two because the samples are autocorrelated: consecutive queue readings
   * are nearly the same reading, so a fitted line has far fewer independent observations than
   * it has samples and the usual two-sigma intuition is badly optimistic here. Four holds the
   * measured false-positive rate at or below ~1 % on realistic stationary 300 s windows while
   * keeping detection above 96 % once true growth reaches ~6 persons/min.
   *
   * A perfect fit has zero residual scatter, so the ratio is `Infinity` and this gate passes:
   * a noiseless straight line is decided by gates 1 and 2 alone.
   */
  readonly minGrowthToNoiseRatio: number;
  /**
   * Smallest slope t-statistic that counts. **Default 2.0** — roughly a two-sided 95% test
   * for the sample sizes used here, rounded to a number worth remembering. See the interface
   * docstring for why this is the weakest of the gates and is never trusted alone.
   */
  readonly minTStatistic: number;
}

/** See {@link SaturationThresholds} for the derivation of each number. */
export const SATURATION_DEFAULTS: SaturationThresholds = Object.freeze({
  minSamples: 8,
  minSlopePersonsPerMinute: 0.5,
  minProjectedGrowthPersons: 8,
  minGrowthToNoiseRatio: 4,
  minTStatistic: 2,
});

/** Where the queue-length series that produced a diagnosis came from. */
export const QUEUE_SERIES_SOURCES = [
  /** `RunRecord.queueSamples`, recorded by the simulation. */
  'recorded',
  /** Reconstructed from arrival and boarding times in the passenger records. */
  'derived',
  /** Neither was available. */
  'none',
] as const;

export type QueueSeriesSource = (typeof QUEUE_SERIES_SOURCES)[number];

/**
 * The saturation verdict, and every number behind it.
 *
 * The diagnostics are not decoration. A flag with no evidence is un-auditable, and the whole
 * point of this test is to be trusted when it overrides a mean that looks perfectly
 * reasonable.
 */
export interface SaturationDiagnosis {
  /** `true` only for {@link SaturationVerdict} `diverging-queue`. */
  readonly saturated: boolean;
  readonly verdict: SaturationVerdict;
  readonly source: QueueSeriesSource;
  /** The window the trend was fitted over. */
  readonly windowStartS: SimTime;
  readonly windowEndS: SimTime;
  readonly sampleCount: number;
  /** Fitted growth, persons per second. */
  readonly slopePersonsPerSecond: number;
  /** Fitted growth, persons per minute — the quantity the threshold is stated in. */
  readonly slopePersonsPerMinute: number;
  /**
   * `slope * windowSeconds`: how many people longer the queue is by the end of the fit.
   *
   * The window-aware magnitude the verdict is actually decided on — see
   * {@link SaturationThresholds.minProjectedGrowthPersons}.
   */
  readonly projectedGrowthPersons: number;
  readonly interceptPersons: number;
  readonly rSquared: number;
  /** Scatter of the queue about the fitted line, persons. The noise yardstick for gate 3. */
  readonly residualStdDevPersons: number;
  /**
   * `projectedGrowthPersons / residualStdDevPersons` — the fitted backlog in units of the
   * queue's own scatter. `Infinity` for a noiseless rising line, `0` when the fit is flat.
   */
  readonly growthToNoiseRatio: number;
  readonly tStatistic: number;
  readonly meanQueueLength: number;
  readonly maxQueueLength: number;
  /** The thresholds actually applied, so a stored verdict can be re-derived. */
  readonly thresholds: SaturationThresholds;
}

/* -------------------------------------------------------------------------- *
 * Summary statistics
 * -------------------------------------------------------------------------- */

/**
 * Location and spread of a set of durations.
 *
 * Every field is `NaN` when {@link count} is zero. See the module docstring: an absent
 * measurement must not arrive downstream disguised as a zero.
 */
export interface DurationStatistics {
  readonly count: number;
  readonly meanS: number;
  /** Sample standard deviation (`n - 1` denominator). `NaN` for `count < 2`. */
  readonly stdDevS: number;
  readonly minS: number;
  readonly medianS: number;
  readonly p90S: number;
  readonly p95S: number;
  readonly p99S: number;
  readonly maxS: number;
  /** Which interpolation produced the percentiles. See {@link PERCENTILE_METHODS}. */
  readonly percentileMethod: PercentileMethod;
}

/**
 * Waiting time: registration at the landing to boarding.
 *
 * The three headline numbers from docs/03-traffic-and-statistics.md § Part 5 are
 * {@link DurationStatistics.meanS} (**AWT**), {@link DurationStatistics.p95S} (**WT95** — what
 * people experience as "bad"; means hide tails) and {@link pctOverLongWait} (**% > 60 s**, the
 * standard long-wait quality metric).
 *
 * Computed over legs that **boarded within the window's cohort**. Legs that arrived in the
 * window and never boarded contribute to {@link unservedCount} and to saturation detection,
 * but not to the mean — a passenger who is still waiting has no waiting time yet, and
 * imputing one would be inventing data.
 *
 * That exclusion makes this a **censored** sample whenever `unservedCount > 0`, and censoring
 * here is not random: the passengers who never boarded are systematically the ones who would
 * have waited longest, so the mean over the survivors is biased *low* exactly when the system
 * is doing worst. {@link RunSummary.awtIsValid} carries an explicit censoring gate for this
 * — see `DEFAULT_MAX_UNSERVED_FRACTION` — which is independent of the queue-trend test,
 * because a window can be badly censored without the fitted trend firing.
 */
export interface WaitStatistics extends DurationStatistics {
  /** Legs whose arrival fell in the window, served or not. */
  readonly arrivalCount: number;
  /** Legs that arrived in the window and had not boarded when the run ended. */
  readonly unservedCount: number;
  /** The long-wait threshold applied. 60 s by default. */
  readonly longWaitThresholdS: number;
  /** Served legs whose wait was **strictly greater** than {@link longWaitThresholdS}. */
  readonly overLongWaitCount: number;
  /**
   * {@link overLongWaitCount} as a percentage of **served** legs, `0`–`100`. `NaN` when none.
   *
   * The denominator is served legs, so this shares the censoring caveat on the interface
   * docstring and shares it in the worse direction: the unserved legs are precisely the ones
   * that would have counted as long waits. `arrivalCount` and {@link unservedCount} are both
   * on this object so the size of that hole is always visible.
   */
  readonly pctOverLongWait: number;
  /** Distribution of waiting times, in seconds. */
  readonly histogram: Histogram;
}

/**
 * Car occupancy over time.
 *
 * **Time-weighted**, computed by holding each {@link LoadSample} until the next sample for the
 * same car (or the end of the window). A car spends far more time near empty than the sample
 * count suggests, because loading events cluster; weighting by sample count would report the
 * distribution of *events*, not of occupancy. See docs/03-traffic-and-statistics.md § Part 5,
 * where this metric exists to "validate the capacity model" — which it can only do if it
 * describes where the cars actually were.
 *
 * ## The empty end of the range has to be in the sample
 *
 * `MetricsRecorder.sampleLoad` is documented to be called "on every load change — each board
 * and each alight", which is exactly right for a step function and has one consequence worth
 * stating: **a car that never carries anybody never produces a sample.** Building the car
 * index from the sample list alone would therefore make an over-provisioned bank look
 * correctly sized — four idle cars out of eight would be indistinguishable from a four-car
 * bank — which is the opposite of validating the capacity model.
 *
 * So the roster is an input, not an inference. `loadFactorStatistics` takes the car ids
 * explicitly (from `RunRecord.carIds`, when the recorder was told them) and seeds a zero-load
 * reading at the window start for every car with no sample at or before it, so idle
 * car-seconds are weighted like any others. {@link sampledCarCount} says how much of
 * {@link carCount} the samples actually covered.
 */
export interface LoadFactorStatistics {
  readonly sampleCount: number;
  /**
   * Cars the distribution covers: the roster, unioned with every car that appears in the
   * samples. Idle cars are included, which is the point.
   */
  readonly carCount: number;
  /**
   * Of {@link carCount}, how many produced at least one real {@link LoadSample}. A gap
   * between the two is idle cars — informative, not an error.
   */
  readonly sampledCarCount: number;
  /** Car-seconds observed inside the window. The histogram's total weight. */
  readonly observedSeconds: number;
  /** Time-weighted mean load factor, or `NaN` with nothing observed. */
  readonly meanLoadFactor: number;
  readonly minLoadFactor: number;
  readonly maxLoadFactor: number;
  /** Fraction of observed car-seconds spent at or above the design load factor, `0`–`1`. */
  readonly fractionOfTimeAtOrAboveDesignLoad: number;
  /** The design load factor that fraction was measured against. 0.8 by default, never 1.0. */
  readonly designLoadFactor: number;
  /** Time-weighted distribution over load-factor bins. */
  readonly distribution: Histogram;
}

/**
 * Persons handled per 5 minutes — the achieved counterpart of the closed-form `HC5` from
 * docs/03-traffic-and-statistics.md § Part 2, and the number the RTT oracle is checked
 * against.
 *
 * **This is the one metric selected by events in the window rather than by arrival cohort.**
 * Throughput is "how many people did the system move during these five minutes", so it counts
 * boardings whose `boardedAt` falls inside the window, including passengers who arrived
 * before it. Counting the arrival cohort instead would credit the window with work done after
 * it and, under saturation, would report a capacity the system never achieved. The two
 * selectors answer different questions and each is wrong for the other's.
 *
 * Boarding, not alighting, is the moment a person is handled: alighting lags by the ride time
 * and would systematically drop the passengers still in the air at the window boundary.
 *
 * ## Persons are people; legs are rides
 *
 * A {@link PassengerRecord} is a **leg**, and in a sky-lobby building one person is two legs.
 * `%POP` is defined by docs/03-traffic-and-statistics.md § Part 2 as `HC5 / population × 100`
 * where the population is *people*, and the demand targets in § Part 1 are quoted in
 * "% pop / 5 min" of people — so counting legs there would inflate the headline number by the
 * transfer factor, and four of the five shipped buildings declare an `isTransferFloor`.
 *
 * The person-denominated fields therefore count **distinct `journeyId`s**, and the
 * `legs*` fields count legs. Both are reported because both are real: legs are what the cars
 * actually did (two rides is two rides' worth of work), persons are what the building
 * delivered. Only the person counts belong in a comparison against the closed-form `HC5`.
 */
export interface HandlingCapacity {
  /** Distinct journeys with at least one boarding inside the window. The `HC5` numerator. */
  readonly personsHandled: number;
  /** Distinct journeys with at least one alighting inside the window. Diagnostic. */
  readonly personsDelivered: number;
  /** Distinct journeys with at least one leg arriving inside the window: demand offered. */
  readonly personsArrived: number;
  /** Boardings inside the window, counting a transfer as the second boarding it is. */
  readonly legsHandled: number;
  /** Alightings inside the window. */
  readonly legsDelivered: number;
  /** Leg arrivals inside the window. */
  readonly legsArrived: number;
  readonly windowSeconds: number;
  /** `personsHandled * 300 / windowSeconds`. The headline HC5, in **people**. */
  readonly personsPer5Min: number;
  /** `personsArrived * 300 / windowSeconds`. Demand in the same units. */
  readonly offeredPer5Min: number;
  /** `legsHandled * 300 / windowSeconds`. Rides delivered — the cars' workload, not %POP. */
  readonly legsPer5Min: number;
  /** Population the demand was generated against, when the record carries it. */
  readonly population?: number | undefined;
  /** `personsPer5Min / population * 100`, the industry's `%POP`. Requires a population. */
  readonly pctPopulationPer5Min?: number | undefined;
}

/**
 * Achieved **interval**: the seconds between successive car departures from the terminal.
 *
 * The other half of Phase 2's acceptance oracle. docs/05-roadmap.md asks that "Midtown Office
 * under pure up-peak produces interval **and** handling capacity matching the closed-form
 * Barney/CIBSE RTT calculation within a few percent"; `analytical/` supplies the closed-form
 * side as `RoundTripResult.intervalS = RTT / L`, {@link HandlingCapacity} supplies the
 * achieved throughput, and this type supplies the achieved interval. Without it half of the
 * project's primary correctness check has nothing to compare against.
 *
 * ## How a departure is reconstructed
 *
 * A run record stores boardings, not departures, so departures are inferred: in-window
 * boardings at the terminal floor are grouped by car, and consecutive boardings by the same
 * car more than `departureGapS` apart start a new departure. A departure's time is its **last**
 * boarding — the moment loading finished and the doors could close. The gaps between
 * successive departures, merged across every car in the group and sorted, are the intervals.
 *
 * ## The spread is not decoration
 *
 * `CLOSED_FORM_ASSUMPTIONS` warns that the closed form assumes cars depart evenly spaced while
 * real groups **bunch**, so a simulated mean interval that matches `INT` while
 * {@link coefficientOfVariation} is large is a *different* finding from a clean match — the
 * average passenger's wait depends on the spacing, not just its mean. Both are reported so
 * that distinction is visible rather than averaged away.
 *
 * Inherited {@link DurationStatistics} fields describe the **gaps**: `count` is the number of
 * gaps (one fewer than {@link departureCount}), `meanS` is the achieved interval, and `p95S`
 * is the tail of the spacing.
 */
export interface IntervalStatistics extends DurationStatistics {
  /**
   * The floor treated as the terminal. Defaults to the floor most in-window boardings
   * happened at — under pure up-peak, the lobby — and is reported so the choice is auditable.
   * `undefined` when there were no in-window boardings to infer one from, or when several
   * terminals were named explicitly and no single one describes the result.
   */
  readonly terminalFloorId?: string | undefined;
  /** Departures reconstructed inside the window, across every car. */
  readonly departureCount: number;
  /** Cars that departed the terminal at least once inside the window. */
  readonly carCount: number;
  /** Boardings those departures were reconstructed from. */
  readonly boardingCount: number;
  /**
   * `stdDevS / meanS` — the bunching measure. `0` for a perfectly regular group, `1` for
   * exponentially spaced departures, `NaN` when there are too few gaps to say.
   */
  readonly coefficientOfVariation: number;
  /** The clustering threshold applied when grouping boardings into departures, seconds. */
  readonly departureGapS: number;
}

/** How many legs and journeys the window contained, and how far each got. */
export interface RunCounts {
  /** Legs whose arrival fell in the window. */
  readonly arrivals: number;
  /** Of those, how many boarded. */
  readonly boarded: number;
  /** Of those, how many completed their leg. */
  readonly alighted: number;
  /** Of those, how many were still waiting when the run ended. */
  readonly unserved: number;
  /** Journeys whose first leg arrived in the window. */
  readonly journeysStarted: number;
  /** Of those, how many reached their final destination. */
  readonly journeysCompleted: number;
  /** Legs recorded in the whole run, in and out of the window. */
  readonly legsInRun: number;
}

/**
 * Everything a run says about itself over one window.
 *
 * Derived, never persisted: a summary is a function of a {@link RunRecord} and a set of
 * options, so re-windowing or re-thresholding a stored run is a re-`summarizeRun()` rather
 * than a re-simulation. It carries the {@link seed} anyway, so a number that turns out to be
 * surprising can be traced back to a replayable run.
 */
export interface RunSummary {
  readonly runId: string;
  /** The seed of the run this summarizes, as a decimal string. */
  readonly seed: string;
  readonly buildingId?: string | undefined;
  readonly dispatcherProfileId?: string | undefined;
  readonly trafficProfileId?: string | undefined;
  /** The window every cohort statistic below was computed over. */
  readonly window: ReportWindow;
  readonly windowSeconds: number;

  readonly counts: RunCounts;
  /** AWT, WT95 and % > 60 s. */
  readonly waiting: WaitStatistics;
  /** In-car time, per leg. */
  readonly rideTime: DurationStatistics;
  /** **TTD**, per journey, spanning every leg and every transfer. */
  readonly timeToDestination: DurationStatistics;
  readonly loadFactor: LoadFactorStatistics;
  readonly handlingCapacity: HandlingCapacity;
  /** **INT**, achieved: the spacing of car departures from the terminal. */
  readonly achievedInterval: IntervalStatistics;
  readonly saturation: SaturationDiagnosis;

  /**
   * Whether {@link waiting}'s mean may carry a confidence interval.
   *
   * `false` on any of three independent grounds:
   *
   * 1. **Saturation** — the queue diverged over the window. docs/03-traffic-and-statistics.md:
   *    "If a configuration saturates, flag it and suppress the AWT interval. Do not report a
   *    mean for a system whose queues grow without bound."
   * 2. **Censoring** — too large a fraction of the window's arrivals were never served, so the
   *    mean is taken over the survivors, who are systematically the passengers who waited
   *    least. See `DEFAULT_MAX_UNSERVED_FRACTION`. This is checked *separately* from the
   *    trend test: recorded queue samples can legitimately overturn the trend verdict (only
   *    the simulation knows why a landing emptied), but nothing can make the mean of the
   *    fastest sixth of a cohort trustworthy.
   * 3. **Emptiness** — nobody was served at all, so there is no mean.
   *
   * Phase 3 reads this and suppresses the interval.
   */
  readonly awtIsValid: boolean;
  /** Why not, when {@link awtIsValid} is `false`. */
  readonly awtInvalidReason?: string | undefined;
}

/* -------------------------------------------------------------------------- *
 * Tunables (CLAUDE.md invariants 7 and 8)
 * -------------------------------------------------------------------------- */

/** Parameter kinds a generic optimizer understands. See docs/06-parameterization-and-tuning.md. */
export type MetricsParameterType = 'continuous' | 'integer' | 'categorical' | 'boolean';

/**
 * A self-describing tunable, in the same shape as `CarParameterSpec` and `DoorParameterSpec`.
 *
 * Repeated here for the reason `model/car/types.ts` documents: this is the generic
 * parameter-schema shape from docs/06-parameterization-and-tuning.md, which has no home
 * module until Phase 7 lands `tuning/`. When it does, all three declarations move there.
 */
export interface MetricsParameterSpec {
  /** Dotted path of the value, e.g. `metrics.longWaitThresholdS`. */
  readonly id: string;
  readonly type: MetricsParameterType;
  /** Inclusive `[min, max]`. Present for `continuous` and `integer`. */
  readonly range?: readonly [number, number] | undefined;
  readonly scale?: 'linear' | 'log' | undefined;
  /** Admissible values. Present for `categorical`. */
  readonly values?: readonly string[] | undefined;
  readonly default: number | string | boolean;
  /** SI unit, or omitted for a dimensionless quantity. */
  readonly unit?: string | undefined;
  readonly description: string;
  /** Parameter id to the values that make this parameter live. */
  readonly activeWhen?: Readonly<Record<string, readonly string[]>> | undefined;
}
